name: Feature Branches build pipeline

on:
  push:
    branches:
      - feature/*

jobs:
  build-pipeline:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Unit Tests
        run: docker-compose run web test
